on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: git.devhack.net/devhack/containers/deployer:latest
    steps:
      - name: rollout kubernetes deployment
        run: |
          set -euo pipefail
          echo "${{ secrets.KUBERNETES_CLIENT_CONFIG }}" > ~/.kube/config
          kubectl -n www rollout restart deployment devhack-net
